//+======================================================================
// $Source$
//
// Project:   Tango
//
// Description:  java source code for the Pogo class definition .
//
// $Author$
//
// $Revision$: $
//
// Copyleft 2003 by European Synchrotron Radiation Facility, Grenoble, France
//               All Rights Reversed
//-======================================================================

package admin.astor; 

import fr.esrf.Tango.*;
import fr.esrf.TangoDs.*;
import fr.esrf.TangoApi.*;

import java.util.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.text.*;


/** 
 *	Display a Server/Device tree to find host where running.
 *
 * @author  verdier
 * @version 
 */
public class DeviceTreeDialog extends javax.swing.JDialog {

	private static final String separator =
		"___________________________________________________";


	private Astor			parent;
	private TangoHost[]		hosts;
	private DeviceTreeDialog	dialog;
	//========================================================
	/**
	 *	Creates new form DeviceTreeDialog
	 */
	//========================================================
	public DeviceTreeDialog(Astor parent, TangoHost[] hosts) {
		super (parent, false);
		this.parent = parent;
		this.hosts  = hosts;
		this.dialog = this;
		
		initComponents ();

		//	Start a Thread to update monitor during database browsing
		new DisplayMonitor().start();

		pack ();
		AstorUtil.rightShiftDialog(this, parent);
	}

	//========================================================
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the FormEditor.
	 */
	//========================================================
	private void initComponents () {//GEN-BEGIN:initComponents
		buttonPanel = new javax.swing.JPanel ();
		cancelButton = new javax.swing.JButton ();
		jScrollPane1 = new javax.swing.JScrollPane ();
		infoLabel = new javax.swing.JTextArea ("   ");
		addWindowListener (new java.awt.event.WindowAdapter () {
		public void windowClosing (java.awt.event.WindowEvent evt) {
			closeDialog (evt);
			}}
		);

		infoLabel.setEditable(false);
		infoLabel.setColumns(30);
		infoLabel.setRows(8);
		//infoLabel.setPreferredSize(new Dimension(400, 120));
		getContentPane ().add (infoLabel, java.awt.BorderLayout.NORTH);

		buttonPanel.setLayout (new java.awt.FlowLayout (2, 5, 5));
		cancelButton.setText ("Dismiss");
		cancelButton.addActionListener (new java.awt.event.ActionListener () {
		public void actionPerformed (java.awt.event.ActionEvent evt) {
			cancelButtonActionPerformed (evt);
			}}
		);
  		buttonPanel.add (cancelButton);
		getContentPane ().add (buttonPanel, java.awt.BorderLayout.SOUTH);

		getContentPane ().add (jScrollPane1, java.awt.BorderLayout.CENTER);

	}//GEN-END:initComponents

	//============================================================
	/**
	 *	Closes the dialog
	 */
	//============================================================
	private void cancelButtonActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
		doClose();
	}//GEN-LAST:event_cancelButtonActionPerformed

	//============================================================
	/**
	 *	Closes the dialog
	 */
	//============================================================
	private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
		doClose();
	}//GEN-LAST:event_closeDialog

	//============================================================
	/**
	 *	Closes the dialog
	 */
	//============================================================
	void doClose () {
		setVisible (false);
		dispose ();
	}
	//======================================================
	//======================================================
	


	//======================================================
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPanel buttonPanel;
	private javax.swing.JButton cancelButton;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea 	infoLabel;
	// End of variables declaration//GEN-END:variables
	//======================================================




	//===============================================================
	//===============================================================
	class DisplayMonitor extends Thread
	{

		private Monitor		monitor;
		//=======================================================
		//=======================================================
		DisplayMonitor()
		{
			monitor = new Monitor(parent,
				"Browsing TANGO database for Servers and Devices....", "");
		}
		//=======================================================
		/**
		 *	Execute the servers commands.
		 */
		//=======================================================
		public void run()
		{
			//	Build the tree (updates the monitor)
			DeviceTree	tree = new DeviceTree(parent, monitor,
					infoLabel, "TANGO " + AstorUtil.getTangoHost());
			//	Show the result
			jScrollPane1.setViewportView (tree);
			setTitle("Tree Dialog");
			pack();
			AstorUtil.rightShiftDialog(dialog, parent);
			monitor.setProgressValue(1.1, "Done");
    		setVisible (true);
		}
	}//	End of DisplayMonitor thread
}
