//+======================================================================
// $Source$
//
// Project:   Tango
//
// Description:  Basic Dialog Class to display info
//
// $Author$
//
// $Revision$
// $Log$
//
//
// Copyleft 2007 by European Synchrotron Radiation Facility, Grenoble, France
//               All Rights Reversed
//-======================================================================

package admin.astor;

import fr.esrf.Tango.*;
import fr.esrf.TangoDs.*;
import fr.esrf.TangoApi.*;


import java.awt.*;
import java.awt.event.*;
import java.io.*;
import java.util.*;
import javax.swing.*;
import fr.esrf.tangoatk.widget.util.*;

//===============================================================
/**
 *	Class Description: Basic Dialog Class to display info
 *
 *	@author  Pascal Verdier
 */
//===============================================================


public class PreferenceDialog extends JDialog
{
	private JFrame	parent;

	//===============================================================
	/**
	 *	Creates new form PreferenceDialog
	 */
	//===============================================================
	public PreferenceDialog(JFrame parent)
	{
		super(parent, true);
		this.parent = parent;
		initComponents();
		initialize();

		titleLabel.setText(AstorUtil.getTangoHost() + "  preferences");
		pack();
        ATKGraphicsUtils.centerDialog(this);
	}
	//===============================================================
	//===============================================================
	private void storePreferences()
	{
		//	Get velues
		rl_user  = rshUserTxt.getText();
		rl_cmd   = rshCmdTxt.getText();

		//	Check them
		if (rl_user==null)              rl_user           = "";
		if (rl_cmd==null)               rl_cmd            = "";
		if (tools==null)                tools             = new String[0];
		if (last_collection==null)      last_collection   = new String[0];
		if (known_tango_hosts==null)    known_tango_hosts = new String[0];
		if (pages==null)                pages             = new String[0];

		//	Set them
		AstorUtil	util = AstorUtil.getInstance();
		util.setJiveReadOnly(jiveReadOnly);
		util.setRloginUser(rl_user);
		util.setRloginCmd(rl_cmd);
		util.setLastCollectionList(last_collection);
		util.setKnownTangoHosts(known_tango_hosts);
		util.setTools(tools);
		util.setHtmlHelps(pages);
		
		try
		{
			//	And write it in database
			util.putAstorProperties();
			app_util.PopupMessage.show(this,
				"The preferences have been saved for " + AstorUtil.getTangoHost());
		}
		catch (DevFailed e)
		{
			ErrorPane.showErrorMessage(this, "Cannot put Astor properties", e);
		}
	}
	//===============================================================
	//===============================================================
	private String[]	last_collection = new String[0];
	private String[]	known_tango_hosts= new String[0];
	private String[]	tools = new String[0];
	private String[]	pages = {
			"Device Servers",
			"http://www.esrf.fr/computing/cs/tango/tango_doc/ds_doc/index.html"
		};
	private String		rl_user = "";
	private String		rl_cmd = "rlogin";
	private boolean		jiveReadOnly = false;
	private void initialize()
	{
		AstorUtil	util = AstorUtil.getInstance();
		
		//	Get last collections
		last_collection = util.getLastCollectionList();

		//	Get known TANGO_HOST
		known_tango_hosts = util.getKnownTangoHosts();
		
		//	Get additianal tools
		tools = util.getTools();

		//	Get help pages
		pages = util.getHtmlHelps();

		//	Get Jive startup mode
		jiveReadOnly = util.jiveIsReadOnly();
		setJiveBtn(jiveReadOnly);

		//	Get rlogin info
		rl_user = util.getRloginUser();
		if (rl_user!=null)
			rshUserTxt.setText(rl_user);
		rl_cmd  = util.getRloginCmd();
		if (rl_cmd!=null)
			rshCmdTxt.setText(rl_cmd);
	}

	//===============================================================
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
	//===============================================================
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        okBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        prefPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rshUserTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rshCmdTxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jiveRObtn = new javax.swing.JRadioButton();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        lastCollectionBtn = new javax.swing.JButton();
        tangoHostsBtn = new javax.swing.JButton();
        toolsBtn = new javax.swing.JButton();
        helpPagesBtn = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okBtn.setText("OK");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        jPanel1.add(okBtn);

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jPanel1.add(cancelBtn);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        titleLabel.setFont(new java.awt.Font("Dialog", 1, 18));
        titleLabel.setText("Dialog Title");
        jPanel2.add(titleLabel);

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        prefPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12));
        jLabel1.setText("Remote login user :");
        jLabel1.setToolTipText("Default user name used for remote login on a host.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        prefPanel.add(jLabel1, gridBagConstraints);

        rshUserTxt.setColumns(12);
        rshUserTxt.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12));
        rshUserTxt.setToolTipText("Default user name used for remote login on a host.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        prefPanel.add(rshUserTxt, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12));
        jLabel2.setText("Remote login command :");
        jLabel2.setToolTipText("Command used for remote login on a host (rlogin, ssh, ...).");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        prefPanel.add(jLabel2, gridBagConstraints);

        rshCmdTxt.setColumns(12);
        rshCmdTxt.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12));
        rshCmdTxt.setText("rlogin");
        rshCmdTxt.setToolTipText("Command used for remote login on a host (rlogin, ssh, ...).");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        prefPanel.add(rshCmdTxt, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        prefPanel.add(jSeparator2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        prefPanel.add(jSeparator3, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12));
        jLabel5.setText("Start Jive in READ_ONLY mode :");
        jLabel5.setToolTipText("Mode to start jive");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        prefPanel.add(jLabel5, gridBagConstraints);

        jiveRObtn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12));
        jiveRObtn.setText("false");
        jiveRObtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jiveRObtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jiveRObtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jiveRObtnActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        prefPanel.add(jiveRObtn, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        prefPanel.add(jSeparator5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        prefPanel.add(jSeparator7, gridBagConstraints);

        lastCollectionBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12));
        lastCollectionBtn.setText("Last Collections :");
        lastCollectionBtn.setToolTipText("List of collections (families) displayed at the end of the control system tree.");
        lastCollectionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastCollectionBtnActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        prefPanel.add(lastCollectionBtn, gridBagConstraints);

        tangoHostsBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12));
        tangoHostsBtn.setText("Known Tango Hosts");
        tangoHostsBtn.setToolTipText("List of   TANGO_HOST known (used to change during execution).");
        tangoHostsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tangoHostsBtnActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        prefPanel.add(tangoHostsBtn, gridBagConstraints);

        toolsBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12));
        toolsBtn.setText("Additional tools :");
        toolsBtn.setToolTipText("List of  additiannal tools (see  Astor pages).");
        toolsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolsBtnActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        prefPanel.add(toolsBtn, gridBagConstraints);

        helpPagesBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12));
        helpPagesBtn.setText("Help pages");
        helpPagesBtn.setToolTipText("List of   help  pages (as tools see Astor pages).");
        helpPagesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpPagesBtnActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        prefPanel.add(helpPagesBtn, gridBagConstraints);

        getContentPane().add(prefPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	//===============================================================
	//===============================================================
    private void helpPagesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpPagesBtnActionPerformed
		JButton	btn = (JButton)evt.getSource();
		GetTextDialog	dlg = new GetTextDialog(this,
				btn.getText(), btn.getToolTipText(), pages);
		if (dlg.showDialog()==JOptionPane.OK_OPTION)
			pages = dlg.getTextLines();
    }//GEN-LAST:event_helpPagesBtnActionPerformed

	//===============================================================
	//===============================================================
    private void toolsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolsBtnActionPerformed
		JButton	btn = (JButton)evt.getSource();
		GetTextDialog	dlg = new GetTextDialog(this,
				btn.getText(), btn.getToolTipText(), tools);
		if (dlg.showDialog()==JOptionPane.OK_OPTION)
			tools = dlg.getTextLines();

     }//GEN-LAST:event_toolsBtnActionPerformed

	//===============================================================
	//===============================================================
    private void tangoHostsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tangoHostsBtnActionPerformed
		JButton	btn = (JButton)evt.getSource();
		GetTextDialog	dlg = new GetTextDialog(this,
				btn.getText(), btn.getToolTipText(), known_tango_hosts);
		if (dlg.showDialog()==JOptionPane.OK_OPTION)
		{
			known_tango_hosts = dlg.getTextLines();
			for (int i=0 ; i<known_tango_hosts.length ; i++)
				System.out.println(known_tango_hosts[i]);
		}
    }//GEN-LAST:event_tangoHostsBtnActionPerformed

	//===============================================================
	//===============================================================
    private void lastCollectionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastCollectionBtnActionPerformed
		
		JButton	btn = (JButton)evt.getSource();
		GetTextDialog	dlg = new GetTextDialog(this,
				btn.getText(), btn.getToolTipText(), last_collection);
		if (dlg.showDialog()==JOptionPane.OK_OPTION)
			last_collection = dlg.getTextLines();
    }//GEN-LAST:event_lastCollectionBtnActionPerformed

	//===============================================================
	//===============================================================
	private void setJiveBtn(boolean b)
	{
		jiveRObtn.setSelected(b);
		jiveRObtn.setText(""+b);
	}
	//===============================================================
	//===============================================================
    private void jiveRObtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jiveRObtnActionPerformed
		jiveReadOnly = (jiveRObtn.getSelectedObjects()!=null);
		setJiveBtn(jiveReadOnly);
    }//GEN-LAST:event_jiveRObtnActionPerformed

	//===============================================================
	//===============================================================
	private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed

		storePreferences(); 
		doClose();
	}//GEN-LAST:event_okBtnActionPerformed

	//===============================================================
	//===============================================================
	private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
		doClose();
	}//GEN-LAST:event_cancelBtnActionPerformed

	//===============================================================
	/**
	 *	Closes the dialog
	 */
	//===============================================================
	private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
		doClose();
	}//GEN-LAST:event_closeDialog

	//===============================================================
	/**
	 *	Closes the dialog
	 */
	//===============================================================
	private void doClose()
	{
		setVisible(false);
		if (parent instanceof Astor)
			dispose();
		else
			System.exit(0);
	}
	//===============================================================
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton helpPagesBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JRadioButton jiveRObtn;
    private javax.swing.JButton lastCollectionBtn;
    private javax.swing.JButton okBtn;
    private javax.swing.JPanel prefPanel;
    private javax.swing.JTextField rshCmdTxt;
    private javax.swing.JTextField rshUserTxt;
    private javax.swing.JButton tangoHostsBtn;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton toolsBtn;
    // End of variables declaration//GEN-END:variables
	//===============================================================




	//===============================================================
	/**
	* @param args the command line arguments
	*/
	//===============================================================
	public static void main(String args[]) {
		new PreferenceDialog(new javax.swing.JFrame()).setVisible(true);
	}

}
