#!/bin/sh
#---------------------------------------------------------
#	
#---------------------------------------------------------

if [ $DISPLAY ]
then
	echo "Display is $DISPLAY"
else
	echo ""
	echo "DISPLAY environment variable is not defined !"
	echo "Please, enter your DISPLAY name."
	read answer
	if [ $answer ]
	then
#		get the end of string to know if ":0" has been set
		start=`expr $answer : '.*:' \| $answer`
		echo "$start "
		if [ $start = $answer ]
		then
			DISPLAY=$answer:0
		else
			DISPLAY=$answer
		fi
		export DISPLAY
		echo "Starting astor on $DISPLAY"
	else
		echo "DISPLAY is not defined ! Astor cannot start !"
		exit
	fi
fi

#---------------------------------------------------------
#	Set the Class Path for Tango and Astor usage
#---------------------------------------------------------
TANGO_HOME=/segfs/tango;                           export TANGO_HOME
TOOLS_HOME=$TANGO_HOME/tools;                      export TOOLS_HOME
LIB_DIR=$TANGO_HOME/lib/java;                      export LIB_DIR
APPLI_HOME=$TANGO_HOME/bin/java;	               export APPLI_HOME
JCLASS_HOME=/segfs/graphics/JClassChart/lib;	   export JCLASS_HOME
API=$TANGO_HOME/javaapi;                          export API

TANGO=$LIB_DIR/TangORB.jar;                          export TANGO
TANGOATK=$LIB_DIR/ATKCore.jar:$LIB_DIR/ATKWidget.jar:$LIB_DIR/ATKtools.jar

ATKPANEL=$APPLI_HOME/atkpanel.jar;                 export ATKPANEL
JIVE=$APPLI_HOME/Jive.jar;                         export JIVE

TANGO=/segfs/tango/lib/java/TangORB.jar

#CLASSPATH=$API:$TANGO:$TOOLS_HOME:$TANGOATK:$ATKPANEL:$JIVE



export CLASSPATH
echo "CLASSPATH=$CLASSPATH"

#---------------------------------------------------------
#	Start the Pogo process
#---------------------------------------------------------
MY_OS=`uname`
export MY_OS
echo ""
echo "Starting Astor Appli under $MY_OS.  Be patient...."
echo "Do not forget, it is a java program...."
echo ""
#

CMD="java	-DTANGO_HOST=$TANGO_HOST	admin.astor.Astor $1 $2 $3 $4"

echo $CMD
$CMD

