#!/bin/sh
#---------------------------------------------------------
#	
#---------------------------------------------------------



ASTOR=../../../bin
CLASSPATH=$ASTOR:$CLASSPATH
export CLASSPATH
echo "CLASSPATH=$CLASSPATH"

#---------------------------------------------------------
#	Start the Pogo process
#---------------------------------------------------------
MY_OS=`uname`
export MY_OS
#
DebugStat=false

CMD="java	admin.astor.statistics.StarterStat $*"
CMD="java  -DebugStat=$DebugStat  admin.astor.statistics.StatisticsPanel $*"

echo $CMD
$CMD

