//+======================================================================
// $Source$
//
// Project:   Tango
//
// Description:  java source code for the TempClass class definition .
//
// $Author$
//
// $Revision$
//
// $Log$
// Revision 1.2  2010/11/30 09:27:47  pascal_verdier
// For multi servers command, if the command is done throu the starter,
// it is done by a thread and a delay has been added between servers.
//
// Revision 1.1  2010/11/29 13:55:30  pascal_verdier
// Multi servers command added.
// Uptime for servers added.
//
//
// Copyleft 2010 by European Synchrotron Radiation Facility, Grenoble, France
//               All Rights Reversed
//-======================================================================

package admin.astor;

/**
 *
 * @author  verdier
 */


import admin.astor.tools.PopupTable;
import fr.esrf.Tango.DevFailed;
import fr.esrf.TangoApi.*;
import fr.esrf.TangoDs.Except;
import fr.esrf.tangoatk.widget.util.ATKGraphicsUtils;
import fr.esrf.tangoatk.widget.util.ErrorPane;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.StringTokenizer;
import java.util.Vector;

//===============================================================
public class MultiServerCommand extends JDialog
{
	private static String	str_filter = "*";
	private static String[]	commands = {
                "",
				"Start",
				"Stop",
                "Status",
				"Uptime",
		};
	//======================================================
	/**
	 *	Creates new form MultiServerCommand
     *  @param parent the parent instance
     * @throws DevFailed in case of database connection failed
	 */
	//======================================================
	public MultiServerCommand(JFrame parent) throws DevFailed
    {
		super (parent, false);
		initComponents ();

		//	fix str filter and add a mouse listener on list
		//---------------------------------------------------
		filterTxt.setText(str_filter);
		MouseListener mouseListener = new MouseAdapter() {
			public void mouseClicked(MouseEvent e) {
				listSelectionPerformed(e);
			}
		};
		jList.addMouseListener(mouseListener);

        for (String cmd : commands)
            comboBox.addItem(cmd);

		setList();
        pack ();
 		ATKGraphicsUtils.centerDialog(this);
	}
    //======================================================
    //======================================================
    private void setList()	throws DevFailed
    {
        str_filter = filterTxt.getText();
        String[] servlist = ApiUtil.get_db_obj().get_server_list(str_filter);
        jList.setListData(servlist);

    }


 	//======================================================
	/** This method is called from within the constructor to
	* initialize the form.
	* WARNING: Do NOT modify this code. The content of this method is
	* always regenerated by the FormEditor.
	*/
 	//======================================================
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        javax.swing.JPanel topPanel = new javax.swing.JPanel();
        javax.swing.JLabel filterLabel = new javax.swing.JLabel();
        filterTxt = new javax.swing.JTextField();
        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane();
        jList = new javax.swing.JList();
        javax.swing.JPanel bottomPanel = new javax.swing.JPanel();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        comboBox = new javax.swing.JComboBox();
        javax.swing.JButton sendCmdBtn = new javax.swing.JButton();
        javax.swing.JButton cancelBtn = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        filterLabel.setText("Filter :  ");
        topPanel.add(filterLabel);

        filterTxt.setColumns(20);
        filterTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterTxtActionPerformed(evt);
            }
        });
        topPanel.add(filterTxt);

        getContentPane().add(topPanel, java.awt.BorderLayout.NORTH);

        scrollPane.setPreferredSize(new java.awt.Dimension(200, 300));
        scrollPane.setViewportView(jList);

        getContentPane().add(scrollPane, java.awt.BorderLayout.CENTER);

        bottomPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Command:");
        jPanel1.add(jLabel1);

        jPanel1.add(comboBox);

        sendCmdBtn.setText("Send");
        sendCmdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendCmdBtnActionPerformed(evt);
            }
        });
        jPanel1.add(sendCmdBtn);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 50);
        bottomPanel.add(jPanel1, gridBagConstraints);

        cancelBtn.setText("Dismiss");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 0);
        bottomPanel.add(cancelBtn, gridBagConstraints);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    //======================================================
    //======================================================
    @SuppressWarnings({"UnusedDeclaration"})
    private void listSelectionPerformed(MouseEvent evt)
    {
    }
	//======================================================
	//======================================================
    @SuppressWarnings({"UnusedDeclaration"})
	private void filterTxtActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterTxtActionPerformed
		try {
			setList();
		}
		catch(DevFailed e)
		{
           	ErrorPane.showErrorMessage(this, "", e);
		}
	}//GEN-LAST:event_filterTxtActionPerformed

	//======================================================
	//======================================================
    @SuppressWarnings({"UnusedDeclaration"})
	private void cancelBtnActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
		setVisible (false);
		dispose ();
	}//GEN-LAST:event_cancelBtnActionPerformed

	//======================================================
	//======================================================
    @SuppressWarnings({"UnusedDeclaration"})
	private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
		setVisible (false);
		dispose ();
	}//GEN-LAST:event_closeDialog

	//======================================================
	//======================================================
    @SuppressWarnings({"UnusedDeclaration"})
	private void sendCmdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendCmdBtnActionPerformed

		//	Get and check selection
		Vector<String>	selections = getSelectedItems();
		if (selections.size()==0) {
			displayError(this, "No server selected !",
				"MultiServerCommand.sendCmdBtnActionPerformed()");
			return;
		}

        //  Get command to be executed
        String	command = (String)comboBox.getSelectedItem();
        if (command.length()==0) {
            displayError(this, "No command selected !",
                "MultiServerCommand.sendCmdBtnActionPerformed()");
            return;
        }

        //	Dispach for command
        if (command.toLowerCase().equals("uptime")) {
            displayServerUptimes(selections);
        } else
        if (command.toLowerCase().equals("status")) {
            displayServerStatus(selections);
        } else {
            starterCommandForServers(command, selections);
        }

	}//GEN-LAST:event_sendCmdBtnActionPerformed
	//======================================================
	//======================================================
	private Vector<String> getSelectedItems()
	{
		Object[]		selections = jList.getSelectedValues();
		Vector<String>	selectedItems = new Vector<String>();
		for (Object obj : selections)
			selectedItems.add(obj.toString());
		return selectedItems;
	}

 	//======================================================
	//======================================================
	public static void displayError(Component component, String desc, String orig)
	{
		try {
			Except.throw_exception("ERROR", desc, orig);
		}
		catch(DevFailed e) {
           	ErrorPane.showErrorMessage(component, "", e);
		}
	}
	//======================================================
	/**
	 * @param args the command line arguments
	 */
	//======================================================
	public static void main (String args[]) {

		try {
			MultiServerCommand	msc = new MultiServerCommand (new JFrame ());
			msc.setVisible(true);
		}
		catch(DevFailed e) {
            ErrorPane.showErrorMessage(new JFrame(), "", e);
		}
	}
 	//======================================================
	//======================================================
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboBox;
    private javax.swing.JTextField filterTxt;
    private javax.swing.JList jList;
    // End of variables declaration//GEN-END:variables
	//======================================================
	//======================================================



 	//======================================================
 	//======================================================
    private static String getHostnameWithoutFQDN(String hostname)
    {
        int pos = hostname.indexOf('.');
        if (pos<0)
            return hostname;
        else
            return hostname.substring(0, pos);
    }
    //======================================================
    //======================================================
    private DeviceProxy getStarterInstanceForServer(String serverName) throws DevFailed
    {
        String devName = "dserver/"+serverName;
        DeviceProxy     dev = new DeviceProxy(devName);
        DeviceInfo info = dev.get_info();
        String hostname = getHostnameWithoutFQDN(info.hostname);

        String  starterDeviceName = "tango/admin/" + hostname;
        return new DeviceProxy(starterDeviceName);
    }
    //======================================================
    //======================================================
    private long getDelayBetweenServers(String message, long defaultValue)
    {
        long    t = -1;
        while (t<0) {
            String	strVal = (String) JOptionPane.showInputDialog(this,
                            message +
                            "\nDelay between servers (ms) ?",
                            "Input Dialog",
                            JOptionPane.INFORMATION_MESSAGE,
                            null, null, defaultValue);
            if (strVal==null)
                return -1;

            try {
                t = Long.parseLong(strVal);
            }
            catch(NumberFormatException e) {
                ErrorPane.showErrorMessage(this, null, e);
            }
        }
        if (t==0)
            t = 10; //  ms
        return t;
    }
    //======================================================
    //======================================================
    private void displayServerUptimes(Vector<String> servNames)
    {
        Vector<String[]>    v = new Vector<String[]>();
        try {
            for (String servName : servNames) {

                String[]    exportedStr = new TangoServer("dserver/"+servName).getServerUptime();
                v.add(new String[] {
                        servName, exportedStr[0], exportedStr[1] } );
            }

            String[]    columns = new String[] { "Server", "Last   exported", "Last unexported" };
            String[][]  table = new String[v.size()][];
            for (int i=0 ; i<v.size() ; i++) {
                table[i] = v.get(i);
            }
            PopupTable ppt = new PopupTable(this, "",
                        columns, table, new Dimension(650, 250));
            ppt.setVisible(true);
        }
        catch(DevFailed e) {
            ErrorPane.showErrorMessage(this, null, e);
        }
    }
    //======================================================
    //======================================================
    private static String convertStatus(String status)
    {
        if (status.equals("ON"))
            return "Running";
        else
        if (status.equals("FAULT"))
            return "Stopped";
        else
        if (status.equals("MOVING"))
            return "Running but NOT responding";
        else
            return status;
    }
    //======================================================
    //======================================================
    private void displayServerStatus(Vector<String> servNames)
    {
        Vector<String[]>    v = new Vector<String[]>();

        for (String servName : servNames) {

            try {
                DeviceProxy starter = getStarterInstanceForServer(servName);
                DeviceAttribute argout = starter.read_attribute("Servers");
                String[]    serverStates = argout.extractStringArray();
                for (String line : serverStates) {
                    StringTokenizer stk = new StringTokenizer(line);
                    String  server = stk.nextToken();
                    String  status = convertStatus(stk.nextToken());
                    if (server.toLowerCase().equals(servName.toLowerCase()))
                        v.add(new String[] { server, status } );
                }
            }
            catch(DevFailed e) {
                v.add(new String[] { servName, e.errors[0].desc } );
            }
        }
        if (v.size()==0) {
            System.err.println("No data found !");
            return;
        }

        String[]    columns = new String[] { "Servers", "Status" };
        String[][]  table = new String[v.size()][];
        for (int i=0 ; i<v.size() ; i++) {
            table[i] = v.get(i);
        }

        try {
            PopupTable ppt = new PopupTable(this, "",
                        columns, table, new Dimension(650, 250));
            ppt.setVisible(true);
        }
        catch(DevFailed e) {
            ErrorPane.showErrorMessage(this, null, e);
        }
    }
    //======================================================
    //======================================================
    private long    delayBetweenServers = 1000;
    private void starterCommandForServers(String command, Vector<String> servNames)
    {
        //  Check for command.
        if (command.equals("Start"))
            command = "DevStart";
        else
        if (command.equals("Stop"))
            command = "DevStop";

        //	Ask to confirm
        long tmpDeleay = getDelayBetweenServers(
                "Send " + command + "  on all selected servers:",
                delayBetweenServers);
        if (tmpDeleay>0) {
            delayBetweenServers = tmpDeleay;
            new CommandThread(this, command, servNames, delayBetweenServers).start();
        }
    }
    //======================================================
    //======================================================



    
    //======================================================
    //======================================================
    private class CommandThread extends Thread
    {
        private Component component;
        private String command;
        private Vector<String> servNames;
        private long delay;
        //======================================================
        private CommandThread (Component component,
                               String command,
                               Vector<String> servNames,
                               long delay)
        {
            this.component = component;
            this.command = command;
            this.servNames = servNames;
            this.delay     = delay;
        }

        //======================================================
        public void run()
        {
            component.setCursor(new Cursor(Cursor.WAIT_CURSOR));
            StringBuffer    sb = new StringBuffer();
            for (String servName : servNames) {

               try {
                   DeviceProxy starter = getStarterInstanceForServer(servName);
                   DeviceData  argin = new DeviceData();
                   argin.insert(servName);
                   starter.command_inout(command, argin);
                   Thread.sleep(delay);
                }
                catch(DevFailed e) {
                   sb.append(e.errors[0].desc).append(" for ").append(servName).append('\n');
                }
                catch (InterruptedException e) {
                    sb.append(e).append(" for ").append(servName).append('\n');
                }
            }
            component.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            if (sb.length()>0)
                displayError(component, sb.toString(),
                        "MultiServerCommand.starterCommandForServers()");
        }
    }
}
