//+======================================================================
// $Source$
//
// Project:   Tango
//
// Description:  java source code for main swing class.
//
// $Author$
//
// $Revision$
// $Log$
// Revision 1.1  2006/09/19 13:06:47  pascal_verdier
// Access control manager added.
//
//
//
// Copyleft 2005 by European Synchrotron Radiation Facility, Grenoble, France
//               All Rights Reversed
//-======================================================================


package admin.astor.access;

import fr.esrf.Tango.DevFailed;
import fr.esrf.TangoApi.*;
import fr.esrf.tangoatk.widget.util.ATKGraphicsUtils;
import fr.esrf.tangoatk.widget.util.ErrorPane;
import fr.esrf.TangoDs.Except;
import fr.esrf.TangoDs.TangoConst;

import javax.swing.*;
import java.awt.*;

//=======================================================
/**
 *	Class Description: Basic JFrame Class to display info
 *
 * @author  Pascal Verdier
 */
//=======================================================
public class TangoAccess extends JFrame
{
	String	access_devname;
    /**
     *	JTree object to display user rights
     */
    private UsersTree	tree = null;
	/**
	 *	Access proxy instance
	 */
	private AccessProxy	access_dev;

    /**
     *  Dialog to check access
     */
    private EditDialog  check_dlg = null;

    /**
     *  True if instancied from another JFrame application.
     */
    private boolean from_another_appli = false;
    //=======================================================
    /**
	 *	Creates new form TangoAccess
	 */
	//=======================================================
    public TangoAccess(JFrame parent) throws DevFailed
	{
        this(parent, null);
    }
    //=======================================================
    /**
	 *	Creates new form TangoAccess
	 */
	//=======================================================
    public TangoAccess(JFrame parent, String devname) throws DevFailed
	{
        if (parent!=null)
            from_another_appli = true;

        if (devname==null)
        {
            //  Get TangoAccess service and check if exist
            String[]    services =
	    		ApiUtil.get_db_obj().getServices("AccessControl", "tango");
            if (services.length==0)
                Except.throw_communication_failed("Service_DoesNotExist",
                        "There is no AccessControl service defined !",
                        "TangoAccess.TangoAccess()");
            access_devname = services[0];
        }
        else
            access_devname = devname;
        initComponents();
        initOwnComponents();
        ImageIcon icon = new ImageIcon(
                getClass().getResource("/app_util/img/tango_icon.jpg"));
        setIconImage(icon.getImage());
        this.setTitle("Tango Access Control Manager");
        pack();
        ATKGraphicsUtils.centerFrameOnScreen(this);
    }
 	//===========================================================
	//===========================================================
	private void initOwnComponents() throws DevFailed
	{
		//	File menu
		fileMenu.setMnemonic ('F');
		addUserBtn.setMnemonic ('U');
		addUserBtn.setAccelerator(KeyStroke.getKeyStroke('U', Event.CTRL_MASK));
		checkAccessBtn.setMnemonic ('T');
		checkAccessBtn.setAccelerator(KeyStroke.getKeyStroke('T', Event.CTRL_MASK));
        exitBtn.setMnemonic ('E');
        exitBtn.setAccelerator(KeyStroke.getKeyStroke('Q', Event.CTRL_MASK));

 		access_dev = new AccessProxy(access_devname);
        if (access_dev.getAccessControl()==TangoConst.ACCESS_READ)
            actionMenu.setVisible(false);
        else
        {
            actionMenu.setMnemonic ('A');
            registerItem.setMnemonic ('R');
        }

         //	Build tree and start threads to update tree
		tree = new UsersTree(this, access_dev);
		JScrollPane scrowllPane = new JScrollPane();
		scrowllPane.setPreferredSize(new Dimension(350, 550));
		scrowllPane.setViewportView (tree);
		getContentPane().add(scrowllPane, BorderLayout.CENTER);
	}
	//=======================================================
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
	//=======================================================
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        javax.swing.JMenuBar jMenuBar1;

        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        addUserBtn = new javax.swing.JMenuItem();
        checkAccessBtn = new javax.swing.JMenuItem();
        exitBtn = new javax.swing.JMenuItem();
        actionMenu = new javax.swing.JMenu();
        registerItem = new javax.swing.JRadioButtonMenuItem();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        fileMenu.setText("File");
        addUserBtn.setText("Add User");
        addUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserBtnActionPerformed(evt);
            }
        });

        fileMenu.add(addUserBtn);

        checkAccessBtn.setText("Test Tango Acces");
        checkAccessBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAccessBtnActionPerformed(evt);
            }
        });

        fileMenu.add(checkAccessBtn);

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        fileMenu.add(exitBtn);

        jMenuBar1.add(fileMenu);

        actionMenu.setText("Action");
        actionMenu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                actionMenuItemStateChanged(evt);
            }
        });

        registerItem.setText("Register Service");
        registerItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerItemActionPerformed(evt);
            }
        });

        actionMenu.add(registerItem);

        jMenuBar1.add(actionMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //=======================================================
    //=======================================================
    private void actionMenuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_actionMenuItemStateChanged
        if (!actionMenu.isSelected())
            return;
        try
        {
            String[]    services =
	    		ApiUtil.get_db_obj().getServices(TangoConst.ACCESS_SERVICE, "tango");
            registerItem.setSelected(services.length!=0);
        }
        catch(DevFailed e)
        {
            ErrorPane.showErrorMessage(this,
				"Cannot start TangoAccess class", e);
        }
    }//GEN-LAST:event_actionMenuItemStateChanged

    //=======================================================
    //=======================================================
    private void registerItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerItemActionPerformed
        try
        {
            boolean b = (registerItem.getSelectedObjects()!=null);
            access_dev.registerService(b);
        }
        catch(DevFailed e)
        {
            ErrorPane.showErrorMessage(this,
				"Cannot start TangoAccess class", e);
        }
    }//GEN-LAST:event_registerItemActionPerformed

    //=======================================================
    //=======================================================
    private void checkAccessBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAccessBtnActionPerformed
        if (check_dlg==null)
        {
            check_dlg = new EditDialog(this, access_dev);
            check_dlg.showDialog();
        }
        else
            check_dlg.setVisible(true);
    }//GEN-LAST:event_checkAccessBtnActionPerformed

    //=======================================================
    //=======================================================
    private void addUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserBtnActionPerformed

        EditDialog  dlg = new EditDialog(this);
        if (dlg.showDialog()==JOptionPane.OK_OPTION)
            tree.addUserNode(dlg.getInputs());
    }//GEN-LAST:event_addUserBtnActionPerformed

	//=======================================================
	//=======================================================
    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        doClose();
    }//GEN-LAST:event_exitBtnActionPerformed

	//=======================================================
    /**
	 *	Exit the Application
	 */
	//=======================================================
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        doClose();
    }//GEN-LAST:event_exitForm

	//=======================================================
	//=======================================================
    private void doClose()
    {
        if (from_another_appli)
            setVisible(false);
        else
            System.exit(0);
    }

   //=======================================================
   /**
    * @param args the command line arguments
    */
	//=======================================================
    public static void main(String args[]) {
        try
        {
            String devname = null;
            if (args.length>0)
                devname = args[0];
            new TangoAccess((JFrame)null, devname).setVisible(true);
        }
        catch (DevFailed e)
        {
            ErrorPane.showErrorMessage(new JFrame(),
				"Cannot start TangoAccess class", e);
            System.exit(0);
        }
    }


	//=======================================================
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu actionMenu;
    private javax.swing.JMenuItem addUserBtn;
    private javax.swing.JMenuItem checkAccessBtn;
    private javax.swing.JMenuItem exitBtn;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JRadioButtonMenuItem registerItem;
    // End of variables declaration//GEN-END:variables
	//=======================================================

}
