#!/bin/sh
#---------------------------------------------------------
#	
#---------------------------------------------------------



ASTOR=../../bin
CLASSPATH=$ASTOR:$CLASSPATH
export CLASSPATH
echo "CLASSPATH=$CLASSPATH"

#---------------------------------------------------------
#	Start the Pogo process
#---------------------------------------------------------

CMD="java admin.astor.Astor $*"

#CMD="java admin.astor.HostInfoDialog $*"

echo $CMD
$CMD 
#2>/dev/null

