//+======================================================================
// $Source$
//
// Project:   Tango
//
// Description:  java source code for the Pogo class definition .
//
// $Author$
//
// $Revision$: $
//
// $Log$
//
// Copyright 2010 by European Synchrotron Radiation Facility, Grenoble, France
//               All Rights Reversed
//-======================================================================

package admin.astor.tools; 

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.text.*;


/** 
 *	Display a message in a scrowled JText
 *
 * @author  verdier
 * @version 
 */
public class PopupText extends javax.swing.JDialog {

	//======================================================
	/**
	 *	Creates new form PopupText
	 */
	//======================================================
	public PopupText(java.awt.Frame parent,boolean modal) {
		super (parent, modal);
		initComponents ();
		pack ();

		try
		{
			//	Put on top left corner
			Point	p = parent.getLocationOnScreen();
			p.x += 10;
			p.y += 10;
			setLocation(p);
		}
		catch(Exception e) { 
			/* is Parent is not already displayed */
		}
		
	}

	//======================================================
	/**
	 *	Creates new form PopupText
	 */
	//======================================================
	public PopupText(JDialog parent,boolean modal) {
		super (parent, modal);
		initComponents ();
		pack ();

		try
		{
			//	Put on top left corner
			Point	p = parent.getLocationOnScreen();
			p.x += 10;
			p.y += 10;
			setLocation(p);
		}
		catch(Exception e) { 
			/* is Parent is not already displayed */
		}
	}

	//======================================================
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the FormEditor.
	 */
	//======================================================
	private void initComponents () {//GEN-BEGIN:initComponents
		buttonPanel = new javax.swing.JPanel ();
		cancelButton = new javax.swing.JButton ();
		jScrollPane1 = new javax.swing.JScrollPane ();
		textPane = new javax.swing.JTextPane ();
        textPane.setFont(new java.awt.Font("monospaced", 1, 12));
		addWindowListener (new java.awt.event.WindowAdapter () {
		public void windowClosing (java.awt.event.WindowEvent evt) {
			closeDialog (evt);
			}}
		);

		buttonPanel.setLayout (new java.awt.FlowLayout (2, 5, 5));

		cancelButton.setText ("Dismiss");
		cancelButton.addActionListener (new java.awt.event.ActionListener () {
		public void actionPerformed (java.awt.event.ActionEvent evt) {
			cancelButtonActionPerformed (evt);
			}}
		);
  
		buttonPanel.add (cancelButton);
		getContentPane ().add (buttonPanel, java.awt.BorderLayout.SOUTH);
		jScrollPane1.setViewportView (textPane);
		getContentPane ().add (jScrollPane1, java.awt.BorderLayout.CENTER);

	}//GEN-END:initComponents

	//============================================================
	//============================================================
	public void setFont(java.awt.Font font)
	{
		textPane.setFont(font);
	}
	//============================================================
	/**
	 *	Closes the dialog
	 */
	//============================================================
	private void cancelButtonActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
		doClose();
	}//GEN-LAST:event_cancelButtonActionPerformed

	//============================================================
	/**
	 *	Closes the dialog
	 */
	//============================================================
	private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
		doClose();
	}//GEN-LAST:event_closeDialog

	//============================================================
	/**
	 *	Closes the dialog
	 */
	//============================================================
	private void doClose () {
		setVisible (false);
		dispose ();
	}

	//============================================================
	/**
	 *	Insert the message in the TextPane with its attributes
	 */
	//============================================================
	private void showMsg(String text, SimpleAttributeSet attrs)
	{
		Document	doc = textPane.getDocument();
		try {
			doc.insertString(doc.getLength(), text, attrs);
		}
		catch(BadLocationException ex) { ex.printStackTrace(); }
	}

	//============================================================
	/**
	 *	format the text and Popup the window.
	 */
	//============================================================
	public void showFormated(String text)
	{
		int	nblines = 0;
		int	start = 0;
		int end;
		while ((end=text.indexOf('\n', start))>=0)
		{
			//	Get line after line
			//---------------------------
			end++;
			String	line = text.substring(start, end);
			SimpleAttributeSet	attrs = new SimpleAttributeSet();

			//	Check if title
			//---------------------
			if (line.indexOf(':')<0)
				StyleConstants.setBold(attrs, false);
			else
				StyleConstants.setBold(attrs, true);
			
			//	Check if state
			//---------------------
			int	start1;
			if ((start1=line.indexOf("Running"))>0)
			{
				showMsg(line.substring(0, start1), attrs);
				StyleConstants.setForeground(attrs, Color.green);
				showMsg(line.substring(start1), attrs);
			}
			else
			if ((start1=line.indexOf("Stopped"))>0)
			{
				showMsg(line.substring(0, start1), attrs);
				StyleConstants.setForeground(attrs, Color.red);
				showMsg(line.substring(start1), attrs);
			}
			else
			{
				StyleConstants.setForeground(attrs, Color.black);
				showMsg(line, attrs);
			}
			start = end;
			nblines++;
		}
		textPane.setEditable(false);
		textPane.setSize(400,300);
		pack();
    	setVisible (true);
	}
	
	
	//============================================================
	/** 
	 *	Display a message in a scrowled JText dialog.
	 */
	//============================================================
	public void show(String text)
	{
		textPane.setText(text);
		textPane.setEditable(false);
		textPane.setSize(400,300);
		pack();
    	setVisible (true);
	}
	//============================================================
	/** 
	 *	Display a message in a scrowled JText dialog.
	 */
	//============================================================
	public void show(String title, String[] array, int width, int height)
	{
		//	Display title
		SimpleAttributeSet	attrs = new SimpleAttributeSet();
		int	fs = StyleConstants.getFontSize(attrs);
		StyleConstants.setBold(attrs, true);
		StyleConstants.setUnderline(attrs, true);
		StyleConstants.setFontSize(attrs, fs+4);
		showMsg(title+"\n\n", attrs);

		StyleConstants.setBold(attrs, false);
		StyleConstants.setUnderline(attrs, false);
		StyleConstants.setFontSize(attrs, fs);

		//	Display lines
		for (int i=0 ; i<array.length ; i++)
			showMsg(array[i] + "\n", attrs);
		textPane.setEditable(false);
		textPane.setPreferredSize(new Dimension(width, height));
		pack();
    	setVisible (true);
	}
	//============================================================
	/** 
	 *	Display a message in a scrowled JText dialog.
	 */
	//============================================================
	public void show(String title, String[] array)
	{
		show(title, array, 800, 600);

	}
	//============================================================
	/** 
	 *	Display a message in a scrowled JText dialog and set dimentions.
	 */
	//============================================================
	public void show(String text, int sizeX, int sizeY)
	{
		textPane.setText(text);
		textPane.setEditable(false);
		textPane.setPreferredSize (new java.awt.Dimension(sizeX, sizeY));
		pack();
    	setVisible (true);
	}
	//============================================================
	/**
	 * @param args the command line arguments
	 */
	//============================================================
	public static void main (String args[]) {
		PopupText	pt = new PopupText (new javax.swing.JFrame (), true);
		pt.show("My Title", new String[] { "Line #1", "line #2", "Bla bla bla !"});
	}

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel buttonPanel;
  private javax.swing.JButton cancelButton;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextPane textPane;
  // End of variables declaration//GEN-END:variables
}
