//+======================================================================
// $Source$
//
// Project:   Tango
//
// Description:  java source code for Tango splash screens.
//
// $Author$
//
// $Revision$
// $Log$
//
// Copyleft 2010 by European Synchrotron Radiation Facility, Grenoble, France
//               All Rights Reversed
//-======================================================================

package admin.astor.tools; 



import java.awt.*;


public class TangoWindow extends javax.swing.JWindow {
	/**
	 *	Window title
	 */
	private	String	title = "  TANGO  Client Application  ";
	/**
	 *	Window author
	 */
	private	String	author = "ESRF  -  Software Engineering Group  ";
	//==========================================================
    /**
	 *	Creates new TangoWindow
	 */
	//==========================================================
	private void windowFactory()
	{
        initComponents();

        collaborationLabel.setIcon(new javax.swing.ImageIcon(
			getClass().getResource(Utils.img_path + "TangoCollaboration.jpg")));
		collaborationLabel.setText("");

		//	Update title
        tangoLabel.setIcon(new javax.swing.ImageIcon(
				getClass().getResource(Utils.img_path+"tango.jpg")));
		titleLabel.setFont(new java.awt.Font("Dialog", 1, 32));
		titleLabel.setText(title);

		//	Update author label
		authorLabel.setText(author);
		
		pack();

		//	Center window
		Toolkit toolkit = Toolkit.getDefaultToolkit();
		Dimension scrsize = toolkit.getScreenSize();
		Dimension appsize = getSize();
		Point	p = new Point();
		p.x = (scrsize.width  - appsize.width)/2;
		p.y = (scrsize.height - appsize.height)/2;
		setLocation(p);

		toFront();
	}
	//==========================================================
    /**
	 *	Constructor
	 */
	//==========================================================
	public TangoWindow()
	{
		windowFactory();
    }
	//==========================================================
    /*
	 *	Constructor
	 */
	//==========================================================
	public TangoWindow(String message)
	{
		if (title!=null)
			title = "  " + message + "  ";
		windowFactory();
    }

	//==========================================================
    /*
	 *	Constructor
	 */
	//==========================================================
	public TangoWindow(String message, String author)
	{
		if (title!=null)
			title = "  " + message + "  ";
		if (author!=null)
			this.author = "  " + author + "  " ;
		windowFactory();
    }
	//==========================================================
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
	//==========================================================
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tangoLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        collaborationLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        //tangoLabel.setText(" ");
        getContentPane().add(tangoLabel, java.awt.BorderLayout.EAST);
		javax.swing.JLabel	dummy = new javax.swing.JLabel("   ");
		dummy.setFont(new java.awt.Font("Dialog", 1, 84));
        getContentPane().add(dummy, java.awt.BorderLayout.SOUTH);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        collaborationLabel.setText("    ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel1.add(collaborationLabel, gridBagConstraints);

        titleLabel.setForeground(java.awt.Color.red);
        titleLabel.setText("titleLabel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel1.add(titleLabel, gridBagConstraints);

        authorLabel.setFont(new java.awt.Font("Dialog", 1, 12));
        authorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        authorLabel.setText("authorLabel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel1.add(authorLabel, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //==========================================================
    //==========================================================
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    //==========================================================
    /**
    * @param args the command line arguments
    */
    //==========================================================
    public static void main(String args[]) {
        new TangoWindow().setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorLabel;
    private javax.swing.JLabel collaborationLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tangoLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

}
