#!/bin/sh
#---------------------------------------------------------
#	
#---------------------------------------------------------
TANGO_HOME=/segfs/tango

#----------------------------------------------
#       Define PATH
#----------------------------------------------
OS=`/csadmin/common/scripts/get_os`

#----------------------------------------------
#       LD_LIBRARY_PATH
#----------------------------------------------
#ZMQ=$TANGO_HOME/release/$OS/lib

ZMQ=$TANGO_HOME/ci/Tango/$OS/lib
JZMQ_TEST=/segfs/tango/transport/jzmq-2.1.2/$OS/lib/
JZMQ_TEST=$JZMQ_TEST:/segfs/tango/transport/zmq3.2.2/$OS/lib/
LD_LIBRARY_PATH=$ZMQ:$JZMQ_TEST

echo LD_LIBRARY_PATH=$LD_LIBRARY_PATH
echo


#----------------------------------------------
#       CLASSPATH
#----------------------------------------------
API=$TANGO_HOME/javaapi/bin

ASTOR=$TANGO_HOME/tools/admin/astor
ASTOR_BIN=$ASTOR/bin

LIB_HOME=$TANGO_HOME/release/java/lib
APPLI_HOME=$TANGO_HOME/release/java/appli

#TANGO=$LIB_HOME/TangORB.jar
TANGO=$TANGO_HOME/javaapi/build-tangorb/TangORB.jar

ATK=$LIB_HOME/ATKWidget.jar:$LIB_HOME/ATKCore.jar:$APPLI_HOME/atkpanel.jar
JIVE=$APPLI_HOME/Jive.jar
PANELS=$APPLI_HOME/tool_panels.jar
LOG_VIEWER=$APPLI_HOME/LogViewer.jar

export CLASSPATH=$API:$ASTOR:$ASTOR_BIN:$TANGO:$ATK:$JIVE:$PANELS:$LOG_VIEWER

echo "CLASSPATH=$CLASSPATH"
echo


#export ZMQ_ENABLE=true
#export ApiTrace=true
